### ISSUE TITLE
Typo On Blog Page

### ISSUE THREAD

**Issue by nobozo** [jmikkola/Athena#1]
This is a little embarrassing because this really has nothing to do with Athena but I couldn't find your email address anywhere. On your "Warming Up to Go" page (which is excellent) there's a minor typo.

"or it’s less mentioned cousin" ->
"or its less mentioned cousin"

**Comment by jmikkola** [comment]
Good catch, thanks! I fixed that (and also added my Twitter account so I'm easier to reach).

**Comment by nobozo** [comment]
On 9/12/2015 11:22 AM, Jeremy Mikkola wrote:

> Good catch, thanks! I fixed that (and also added my Twitter account so
> I'm easier to reach).

That's good, but there's still nothing like a good old email account
for those of us who are so retro that we don't use Twitter.

Jon
